[zh-cn]
    languageName = "简体中文"
    title        = "impself小破站"
    weight       = 1
    [zh-cn.params.sidebar]
        subtitle = "擅长面向搜索引擎编程，AI编程"

[en]
    languageName = "English"
    title        = "impself's Little Blog"
    weight       = 2
    [en.params.sidebar]
        subtitle = "Card-style Hugo theme designed for bloggers"


[zh-hant-tw]
    languageName = "正體中文"
    title        = "impself小破站"
    weight       = 3
    [zh-hant-tw.params.sidebar]
        subtitle = "為博客設計的卡片式 Hugo 主題"

[ja]
    languageName = "日本語"
    title        = "impself小破站"
    weight       = 4
    [ja.params.sidebar]
        subtitle = "ブログ用のカードスタイルの Hugo テーマ"
