mainSections   = ["post"]
rssFullContent = true
favicon        = "img/you2.jpg"

[footer]
    since = 2026

[sidebar]
    emoji    = "ðŸ¤–"
    subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    [sidebar.avatar]
        enabled = true
        src     = "img/you2.jpg"

[article]
    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        
        { type = "archives", params = { limit = 5 } },
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
        { type = "about" },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "disqus"
